FROM mcr.microsoft.com/powershell:6.1.0-ubuntu-18.04

#environment
ENV PORT 8080

ENV TITLE "Hello Techorama"

#copy the website and set working directory
COPY  /website /app
COPY /Polaris /app/Polaris
COPY /PSHTML /app/PSHTML